services:
  termix:
    image: ghcr.io/lukegus/termix:release-1.11.0
    container_name: ${CONTAINER_NAME}
    restart: always

    labels:
      createdBy: "Apps"
    ports:
      - ${PANEL_APP_PORT_HTTP}:8080
            
    networks:
      - 1panel-network
    volumes:
      - ./data:/app/data
    environment:
      PORT: "8080"

networks:
  1panel-network:
    external: true
