services:
  chronoframe:
    image: ghcr.io/hoshinosuzumi/chronoframe:0.14.1
    container_name: ${CONTAINER_NAME}
    ports:
      - "${PANEL_APP_PORT_HTTP}:3000"
    environment:
      - CFRAME_ADMIN_NAME=${PANEL_APP_ADMIN_NAME}
      - CFRAME_ADMIN_EMAIL=${PANEL_APP_ADMIN_EMAIL}
      - CFRAME_ADMIN_PASSWORD=${PANEL_APP_ADMIN_PASSWORD}

      - NUXT_PUBLIC_APP_TITLE=${PANEL_APP_SITE_TITLE}
      - NUXT_PUBLIC_APP_SLOGAN=${PANEL_APP_SITE_SLOGAN}
      - NUXT_PUBLIC_APP_AUTHOR=${PANEL_APP_SITE_AUTHOR}
      - NUXT_PUBLIC_APP_AVATAR_URL=${PANEL_APP_SITE_AVATAR_URL}

      - NUXT_STORAGE_PROVIDER=${PANEL_APP_STORAGE_PROVIDER}

      - NUXT_PROVIDER_LOCAL_PATH=${PANEL_APP_LOCAL_PATH}
      - NUXT_PROVIDER_LOCAL_BASE_URL=${PANEL_APP_LOCAL_BASE_URL}

      - NUXT_PROVIDER_S3_ENDPOINT=${PANEL_APP_S3_ENDPOINT}
      - NUXT_PROVIDER_S3_BUCKET=${PANEL_APP_S3_BUCKET}
      - NUXT_PROVIDER_S3_REGION=${PANEL_APP_S3_REGION}
      - NUXT_PROVIDER_S3_ACCESS_KEY_ID=${PANEL_APP_S3_ACCESS_KEY_ID}
      - NUXT_PROVIDER_S3_SECRET_ACCESS_KEY=${PANEL_APP_S3_SECRET_ACCESS_KEY}
      - NUXT_PROVIDER_S3_PREFIX=${PANEL_APP_S3_PREFIX}
      - NUXT_PROVIDER_S3_CDN_URL=${PANEL_APP_S3_CDN_URL}

      - NUXT_PROVIDER_OPENLIST_BASE_URL=${PANEL_APP_OPENLIST_BASE_URL}
      - NUXT_PROVIDER_OPENLIST_ROOT_PATH=${PANEL_APP_OPENLIST_ROOT_PATH}
      - NUXT_PROVIDER_OPENLIST_TOKEN=${PANEL_APP_OPENLIST_TOKEN}
      - NUXT_PROVIDER_OPENLIST_ENDPOINT_UPLOAD=${PANEL_APP_OPENLIST_ENDPOINT_UPLOAD}
      - NUXT_PROVIDER_OPENLIST_ENDPOINT_DOWNLOAD=${PANEL_APP_OPENLIST_ENDPOINT_DOWNLOAD}
      - NUXT_PROVIDER_OPENLIST_ENDPOINT_LIST=${PANEL_APP_OPENLIST_ENDPOINT_LIST}
      - NUXT_PROVIDER_OPENLIST_ENDPOINT_DELETE=${PANEL_APP_OPENLIST_ENDPOINT_DELETE}
      - NUXT_PROVIDER_OPENLIST_ENDPOINT_META=${PANEL_APP_OPENLIST_ENDPOINT_META}
      - NUXT_PROVIDER_OPENLIST_PATH_FIELD=${PANEL_APP_OPENLIST_PATH_FIELD}
      - NUXT_PROVIDER_OPENLIST_CDN_URL=${PANEL_APP_OPENLIST_CDN_URL}

      - NUXT_SESSION_PASSWORD=${PANEL_APP_SESSION_PASSWORD}
    volumes:
      - ./data:/app/data
    labels:
      createdBy: "Apps"
    networks:
      - 1panel-network
    restart: always

networks:
  1panel-network:
    external: true
