services:
  picimpact:
    image: besscroft/picimpact:v2.9.7
    container_name: ${CONTAINER_NAME}
    restart: always
    labels:
      createdBy: "Apps"
    ports:
      - ${PANEL_APP_PORT_HTTP}:3000
    environment:
      DIRECT_URL: postgresql://${PANEL_DB_USER}:${PANEL_DB_USER_PASSWORD}@${PANEL_DB_HOST}:${PANEL_DB_PORT}/${PANEL_DB_NAME}
      DATABASE_URL: postgresql://${PANEL_DB_USER}:${PANEL_DB_USER_PASSWORD}@${PANEL_DB_HOST}:${PANEL_DB_PORT}/${PANEL_DB_NAME}
      BETTER_AUTH_SECRET: ${HASH_SALT}
      BETTER_AUTH_URL: https://${PANEL_APP_DOMAIN}
      BETTER_AUTH_PASSKEY_RP_ID: ${PANEL_APP_DOMAIN}
      BETTER_AUTH_PASSKEY_RP_NAME: ${PASSKEY_NAME}
    networks:
      - 1panel-network
      
networks:
  1panel-network:
    external: true