services:
  picimpact:
    image: besscroft/picimpact:v2.9.6
    container_name: ${CONTAINER_NAME}
    restart: always
    labels:
      createdBy: "Apps"
    ports:
      - ${PANEL_APP_PORT_HTTP}:3000
    environment:
      DIRECT_URL: postgresql://${PANEL_DB_USER}:${PANEL_DB_USER_PASSWORD}@${PANEL_DB_HOST}:${PANEL_DB_PORT}/${PANEL_DB_NAME}
      DATABASE_URL: postgresql://${PANEL_DB_USER}:${PANEL_DB_USER_PASSWORD}@${PANEL_DB_HOST}:${PANEL_DB_PORT}/${PANEL_DB_NAME}
      BETTER_AUTH_SECRET: ${HASH_SALT}
    networks:
      - 1panel-network
      
networks:
  1panel-network:
    external: true