services:
  axonhub_mysql:
    image: looplj/axonhub:v0.7.8
    container_name: ${CONTAINER_NAME}
    restart: always
    environment:
      AXONHUB_DB_DIALECT: mysql
      AXONHUB_DB_DSN: ${PANEL_DB_USER}:${PANEL_DB_USER_PASSWORD}@tcp(${PANEL_DB_HOST}:${PANEL_DB_PORT})/${PANEL_DB_NAME}?charset=utf8mb4&parseTime=True&loc=Local
    volumes:
      - ./data/data:/data
      - ./data/config.yml:/app/config.yml:ro
    ports:
      - "${PANEL_APP_PORT_HTTP}:8090"
    labels:
      createdBy: "Apps"
    networks:
      - 1panel-network

networks:
  1panel-network:
    external: true
